project:
  type: website
  output-dir: docs

website:
  title: "Mastermind Trivia"

  navbar:
    background: primary
    reader-mode: true
    search: true
  
    repo-url: https://github.com/Alex-and-Noah/Mastermind-Trivia
    repo-actions: [edit, issue]

    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/Alex-and-Noah/Mastermind-Trivia
          - text: Report a Bug
            url:  https://github.com/Alex-and-Noah/Mastermind-Trivia/issues

    left:
      - text: Secret
        file: index.qmd
      - text: Secret Noah
        file: index_noah.qmd
    
page-footer:  
  - icon: github
    href: https://github.com/Alex-and-Noah

lang: en

format:
  html:
    theme: 
      light: zephyr
      dark: darkly
    # css: styles.css
    toc: true
    # grid:
    #   sidebar-width: 0px
    #   body-width: 1200px
    #   margin-width: 300px
    #   gutter-width: 1.5rem