---
title: "Mastermind Trivia"
format:
  revealjs:
    transition: slide
    background-transition: fade
    theme: solarized
    incremental: true
css: styles.css
---

# About this quiz

These questions will start easy and get harder--so watch out! Everyone will play against the mastermind on their given topic.

## About the questions {.smaller}

Below are the types of questions you'll see:

1. Multiple-choice
    - The easiest question to get yourself situated
2. Open
    - It gets a little harder when you don't have options anymore
3. Ranking
    - Can you put them in the right order?

---

## About the questions, cont'd {.smaller}

4. Sound-bite
    - I'll play a sound clip and you'll have to answer the question related to it
5. Range
    - Unlike the other questions so far, whoever is closest will get this point
6. Who/What am I?
    - You'll get 3 clues, if you can get the person/object on the first clue that'll be worth 3 points, 2 for the second clue, and 1 for the last clue--pending you get the right answer

## About the scoring

We'll calculate the differentials between the mastermind and the rest of the team--whoever has the highest differential wins.

However, if there is a tie I have some OT questions to break it.

# Alex: Veep {.content-background background-image="./static/veep_background.jpg" background-size="auto 100%" style="width:fit-content;margin-top:25%;padding-left:40px;padding-right:40px;padding-top:5px;padding-bottom:5px;border:2px solid #002b36"}

## Question 1

::: footer
Alex - Veep
:::

Julia Louis-Dreyfus won the Primetime Emmy for Outstanding Lead Actress in a Comedy Series due to her performance in each of the first 6 seasons of Veep. She was nominated for the 7th season but lost to whom?

:::{.incremental}
a. Catherine O'Hara for Schitt's Creek as Moira Rose
b. Phoebe Waller-Bridge for Fleabag
c. Natasha Lyonne for Russian Doll as Nadia
d. Christina Applegate for Dead to Me as Jen
:::

## Question 2

::: footer
Alex - Veep
:::

What does Vice President Selina Meyer wear in the first scene of every first episode of each season?

## Question 3

::: footer
Alex - Veep
:::

List these guests in chronological order of appearance.

:::{.incremental}
a. Patton Oswalt as Teddy Sykes
b. Rhea Seehorn as Michelle York
c. Hugh Laurie as Tom James
d. Christopher Meloni as Ray Whelans
e. Clea DuVall as Majorie Palmiotti
:::

## Question 4

::: footer
Alex - Veep
:::

What is Selina Meyer referring to in this clip?

## Question 5

::: footer
Alex - Veep
:::

Throughout the entire series, how many days did Selina Meyer serve as president?

## Question 6

::: footer
Alex - Veep
:::

Who/what am I?

::: {.incremental}
- I am once described as "[Selena's] two big, very busy webbed legs and feet"
- Using me for too long may necessitate a visit from a masseur
- Some may jokingly call you a *Kassi* if they saw you with me, which is a Finnish slang term for *testicles*
:::

## Answer 1

::: footer
Alex - Veep
:::

Julia Louis-Dreyfus won the Primetime Emmy for Outstanding Lead Actress in a Comedy Series due to her performance in each of the first 6 seasons of Veep. She was nominated for the 7th season but lost to whom?

:::{.incremental}
- **b. Phoebe Waller-Bridge for Fleabag**
:::

## Answer 2

::: footer
Alex - Veep
:::

What does Vice President Selina Meyer wear in the first scene of every first episode of each season?

:::{.incremental}
- **A red dress**
:::

## Answer 3

::: footer
Alex - Veep
:::

List these guests in chronological order of appearance.

:::{.incremental}
d. **Christopher Meloni as Ray Whelans (S3E6)**
a. **Patton Oswalt as Teddy Sykes (S4E1)**
c. **Hugh Laurie as Tom James (S4E5)**
e. **Clea DuVall as Majorie Palmiotti (S5E1)**
b. **Rhea Seehorn as Michelle York (S7E2)**
:::

## Answer 4

::: footer
Alex - Veep
:::

What is Selina Meyer referring to in this clip?

:::{.incremental}
- **Catherine's hair**
:::

## Answer 5

::: footer
Alex - Veep
:::

Throughout the entire series, how many days did Selina Meyer serve as president?

:::{.incremental}
- **1825**
:::

## Answer 6

::: footer
Alex - Veep
:::

Who/what am I?

::: {.nonincremental}
- I am once described as "[Selena's] two big, very busy webbed legs and feet"
- Using me for too long may necessitate a visit from a masseur
- Some may jokingly call you a *Kassi* if they saw you with me, which is a Finnish slang term for *testicles*
:::

<br>

:::{.incremental}
- **The Leviathan (Gary's bag)**
:::

# Noah: Metal Music {.content-background background-image="./static/noah.jpeg" background-size="auto 100%" background-repeat="repeat" style="width:fit-content;margin-top:25%;padding-left:40px;padding-right:40px;padding-top:5px;padding-bottom:5px;border:2px solid #002b36"}

## Question 1

::: footer
Noah - Metal Music
:::

Which of the following well-known 1960s bands is not considered a pioneer of heavy metal?

a. Led Zeppelin
b. The Rolling Stones
c. Deep Purple
d. Black Sabbath

## Question 2

::: footer
Noah - Metal Music
:::

This northern European city was considered an early metal music hub.

## Question 3

::: footer
Noah - Metal Music
:::

Order the "mainstream" appearance of each metal subgenre from earliest to latest:

a. Doom Metal
b. Alternative Metal
c. Thrash Metal
d. Death Metal
e. Grunge Metal


## Question 4

::: footer
Noah - Metal Music
:::

Which metal-inspired artist is featured in this clip?

## Question 5

::: footer
Noah - Metal Music
:::

BABYMETAL are a Nu Metal Group from Japan. As of July 13th. How many plays does their top song have on Spotify?


## Question 6

::: footer
Noah - Metal Music
:::

What am I?

::: {.incremental}
- This style evolved out of progressive metal and was popularized by the internet in the early 2000s.
- This style heavily uses syncopated riffs, distortions and polyrhythms.
- This style characteristically uses 7, 8 or even 9 stringed-guitars.
:::


## Answers

## Question 1

::: footer
Noah - Metal Music
:::

Which of the following well-known 1960s bands is not considered a pioneer of heavy metal?

a. Led Zeppelin
b. **The Rolling Stones**
c. Deep Purple
d. Black Sabbath

## Question 2

::: footer
Noah - Metal Music
:::

This northern European city was considered an early metal music hub.

**Gothenburg, Sweden**

## Question 3

::: footer
Noah - Metal Music
:::

Order the "mainstream" appearance of each submetal genre from earliest to latest:

a. Thrash Metal (1980s)
b. Death Metal (mid 1980s)
c. Doom Metal (late 1980s - early 90s)
d. Grunge Metal (mid 1990s)
e. Alternative Metal (early 2000s)

## Question 4

::: footer
Noah - Metal Music
:::

Which metal-inspired artist is featured in this clip?

**Evanescence**

## Question 5

::: footer
Noah - Metal Music
:::

BABYMETAL are a Nu Metal Group from Japan. As of July 13th. How many plays does their top song have on Spotify?

143,910,465

## Question 6

::: footer
Noah - Metal Music
:::

What am I? 

- This style evolved out of progressive metal.
- This style heavily uses syncopated riffs, distortions and polyrhythms.
- This style characteristically uses 7, 8 or even 9 stringed-guitars.

**Djent**


# Tyler: One Piece  {.content-background background-image="./static/one_piece_background.jpg" background-size="auto 100%" style="width:fit-content;margin-top:25%;padding-left:40px;padding-right:40px;padding-top:5px;padding-bottom:5px;border:2px solid #002b36"}

## Question 1

::: footer
Tyler - One Piece
:::

The first video game based on the One Piece franchise is strategy game **Pirate King**, released in Japan in 2000. On which console was this game released?

:::{.incremental}
a. WonderSwan
b. Game Boy Color
c. PlayStation 1
d. GameCube
:::

## Question 2

::: footer
Tyler - One Piece
:::

What is the name of the fruit that Luffy eats, granting his body the properties of rubber?

## Question 3

::: footer
Tyler - One Piece
:::

Sort the following Straw Hat members based on their first bounties (high to low)

:::{.incremental}
a. Nami
b. Sanji
c. Chopper
d. Roronoa Zoro
e. Usopp
:::

## Question 4

::: footer
Tyler - One Piece
:::

In this scene, what item is Luffy making from scratch to aid him in his fight?

## Question 5

::: footer
Tyler - One Piece
:::

The manga series holds the Guinness World Record for the 'Most copies published for the same comic book series by a single author' (July 2022). How many copies have been published?

## Question 6

::: footer
Tyler - One Piece
:::

Who/what am I?

::: {.incremental}
- I may not be the tallest, coming in at 21ft and 10in tall, but I definitely am the strongest
- Oddly enough, I am named after the real life pirate Blackbeard
- You may have heard me when I yelled "THE ONE PIECE... THE ONE PIECE IS REAL!!!!!"
:::

## Answer 1

::: footer
Tyler - One Piece
:::

The first video game based on the One Piece franchise is strategy game **Pirate King**, released in Japan in 2000. On which console was this game released?

:::{.incremental}
- **a. WonderSwan**
:::

## Answer 2

::: footer
Tyler - One Piece
:::

What is the name of the fruit that Luffy eats, granting his body the properties of rubber?

:::{.incremental}
- **Hito Hito no Mi, Model: Nika (will accept Human-Human Fruit, Gomu Gomu no Mi or Gum-Gum fruit)**
:::

## Answer 3

::: footer
Tyler - One Piece
:::

Sort the following Straw Hat members based on their first bounties (high to low)

:::{.incremental}
b. **Sanji (77,000,000)**
d. **Roronoa Zoro (60,000,000)**
e. **Usopp (30,000,000)**
a. **Nami (16,000,000)**
c. **Chopper (50)**
:::

## Answer 4

::: footer
Tyler - One Piece
:::

In this scene, what item is Luffy making from scratch to aid him in his fight?

:::{.incremental}
- **Baseball bat**
:::

## Answer 5

::: footer
Tyler - One Piece
:::

The manga series holds the Guinness World Record for the 'Most copies published for the same comic book series by a single author' (July 2022). How many copies have been published?

:::{.incremental}
- **416,566,000**
:::

## Answer 6

::: footer
Tyler - One Piece
:::

Who/what am I?

:::{.nonincremental}
- I may not be the tallest, coming in at 21ft and 10in tall, but I definitely am the strongest
- Oddly enough, I am named after the real life pirate Blackbeard
- You may have heard me when I yelled "THE ONE PIECE... THE ONE PIECE IS REAL!!!!!"
:::

<br>

:::{.incremental}
- **Edward Newgate (Whitebeard)**
:::

# Hayley: Grade 9 Geography {.content-background background-image="./static/hayley.jpg" background-size="100%" style="width:fit-content;margin-top:25%;padding-left:40px;padding-right:40px;padding-top:5px;padding-bottom:5px;border:2px solid #002b36"}

## Question 1

::: footer
Hayley - Grade 9 Geography
:::

Which province produces the most hydroelectric power?

a. Ontario
b. Quebec
c. British Columbia
d. Alberta

## Question 2

::: footer
Hayley - Grade 9 Geography
:::

Which natural resource industry employs the most people in Canada?

## Question 3

::: footer
Hayley - Grade 9 Geography
:::

Order these Canadian demographic events:

a. Canada's population surpasses 30 million
b. Millenials outnumbered Baby Boomers
c. Canada's total fertility rate drops below 2 babies per female
d. The first Gen Alpha is born
e. Nunavut becomes a territory

## Question 4

::: footer
Hayley - Grade 9 Geography
:::

What location is "discovered" in this [Heritage Minute](https://www.historicacanada.ca/productions/minutes/jean-nicollet)?

## Question 5

::: footer
Hayley - Grade 9 Geography
:::

How many square km is the Canadian shield?

## Question 6

::: footer
Hayley - Grade 9 Geography
:::

What am I?

::: {.incremental}
- I am shared by Canada and the US and am named after a Greek explorer.
- I last caused a major earthquake in 1700.
- I am a microplate in the ring of fire.
:::

## Answers

## Question 1

::: footer
Hayley - Grade 9 Geography
:::

Which province produces the most hydroelectric power?

a. Ontario
b. **Quebec**
c. British Columbia
d. Alberta

## Question 2

::: footer
Hayley - Grade 9 Geography
:::

Which natural resource industry employs the most people in Canada?

**Minerals and metals**

## Question 3

::: footer
Hayley - Grade 9 Geography
:::

Order these Canadian demographic events:

a. Canada's total fertility rate drops below 2 babies per female (1972)
b. Nunavut becomes a territory (1999)
c. Canada's population surpasses 30 million (2001)
d. The first Gen Alpha is born (2010)
e. Millenials outnumbered Baby Boomers (2023)

## Question 4

::: footer
Hayley - Grade 9 Geography
:::

What location is "discovered" in this [Heritage Minute](https://www.historicacanada.ca/productions/minutes/jean-nicollet)?

**Lake Michigan**

## Question 5

::: footer
Hayley - Grade 9 Geography
:::

How many square km is the Canadian shield?

**8,000,000 km^2**

## Question 6

::: footer
Hayley - Grade 9 Geography
:::

What am I? 

- I am shared by Canada and the US and am named after a Greek explorer.
- I last caused a major earthquake in 1700.
- I am a microplate in the ring of fire.

**Juan de Fuca Plate**


# Michael: Yacht Rock  {.content-background background-image="./static/yacht_rock_background.webp" background-size="auto 100%" style="width:fit-content;margin-top:25%;padding-left:40px;padding-right:40px;padding-top:5px;padding-bottom:5px;border:2px solid #002b36"}

## Question 1

::: footer
Michael - Yacht Rock
:::

Who coined the term 'Yacht Rock'?

:::{.incremental}
a. John Oates
b. J.D. Ryznar
c. Jimmy Buffet
d. Brian Wilson
:::

## Question 2

::: footer
Michael - Yacht Rock
:::

Who wrote the anthemic, archetypical 1979 Yacht Rock song 'Sailing'?

## Question 3

::: footer
Michael - Yacht Rock
:::

List these Beach Boys albums in chronological order of release

:::{.incremental}
a. Smiley Smile
b. Pet Sounds
c. Still Cruisin'
d. All Summer Long
e. Surfin' U.S.A.
:::

## Question 4

::: footer
Michael - Yacht Rock
:::

Name each of these songs and their artists.

## Question 5

::: footer
Michael - Yacht Rock
:::

How many members were in the most recent touring lineup of Steely Dan?

## Question 6

::: footer
Michael - Yacht Rock
:::

What band am I?

::: {.incremental}
- I composed (most of the) soundtrack for the 1984 movie Dune
- I was formed by David Paich and Jeff Porcaro in 1977
- As I've said many times, "It's going to take a lot to drag me away from you"
:::

## Answer 1

::: footer
Michael - Yacht Rock
:::

Who coined the term 'Yacht Rock'?

:::{.incremental}
- **b. J.D. Ryznar**
:::

## Answer 2

::: footer
Michael - Yacht Rock
:::

Who wrote the anthemic, archetypical 1979 Yacht Rock song 'Sailing'?

:::{.incremental}
- **Christopher Cross**
:::

## Answer 3

::: footer
Michael - Yacht Rock
:::

List these Beach Boys albums in chronological order of release

:::{.incremental}
e. **Surfin' U.S.A. (1963)**
d. **All Summer Long (1964)**
b. **Pet Sounds (1966)**
a. **Smiley Smile (1967)**
c. **Still Cruisin' (1989)**
:::

## Answer 4

::: footer
Michael - Yacht Rock
:::

Name each of these songs and their artists.

:::{.incremental}
1. **Footloose by Kenny Loggins**
2. **Hold the Line by Toto**
3. **The Chain by Fleetwood Max**
4. **Cold as Ice by Foreigner**
5. **The Joker by Steve Miller Band**
:::

## Answer 5

::: footer
Michael - Yacht Rock
:::

How many members were in the most recent touring lineup of Steely Dan?

:::{.incremental}
- **13**
:::

## Answer 6

::: footer
Michael - Yacht Rock
:::

What band am I?

:::{.nonincremental}
- I composed (most of the) soundtrack for the 1984 movie Dune
- I was formed by David Paich and Jeff Porcaro in 1977
- As I've said many times, "It's going to take a lot to drag me away from you"
:::

<br>

:::{.incremental}
- **Toto**
:::


# Bhagy: Brooklyn 99 {.content-background background-image="./static/bhagy.jpg" background-size="100%" style="width:fit-content;margin-top:25%;padding-left:40px;padding-right:40px;padding-top:5px;padding-bottom:5px;border:2px solid #002b36"}

## Question 1

::: footer
Bhagy - Brooklyn 99
:::

What is Terry's wife's name?

a. Linda
b. Susan
c. Sharon
d. Erin

## Question 2

::: footer
Bhagy - Brooklyn 99
:::

What mobile game does Holt become addicted to?

## Question 3

::: footer
Bhagy - Brooklyn 99
:::

Order these minor characters by number of episode appearances (highest to lowest)

a. Cheddar
b. Caleb John Gosche
c. Madeline Wuntch
d. Bill Hummertrout
e. Adrian Pimento

## Question 4

::: footer
Bhagy - Brooklyn 99
:::

What is happening to Charles in this [soundbite](https://youtu.be/Xu-VaMy9sFQ?si=95CPKOY63Rn5O7A9&t=914)?

## Question 5

::: footer
Bhagy - Brooklyn 99
:::

In Season 1 Jake Peralta discovers he owes back rent on his grandmother's appartment after failing to open the mail. How much does he owe?


## Question 6

::: footer
Bhagy - Brooklyn 99
:::

Who am I?

::: {.incremental}
- I am allegedly "haunted" by the spirit of a 1920s mobster's mistress.
- Charles leaves me to Jake and Amy in his will.
- I require a highly specific, disgusting daily feeding ritual and I am the secret behind the Boyle family's legendary pizza crust.
:::

## Question 1

::: footer
Bhagy - Brooklyn 99
:::

What is Terry's wife's name?

a. Linda
b. Susan
c. **Sharon**
d. Erin

## Question 2

What mobile game does Holt become addicted to?

**Kwazy Cupcakes**

## Question 3

Order these minor characters by number of episode appearances (highest to lowest)

e. Adrian Pimento (13)
c. Madeline Wuntch (12)
a. Cheddar (9)
d. Bill Hummertrout (7)
b. Caleb John Gosche (4)


## Question 4

::: footer
Bhagy - Brooklyn 99
:::

What is happening to Charles in this [soundbite](https://youtu.be/Xu-VaMy9sFQ?si=95CPKOY63Rn5O7A9&t=914)?

**Rosa is shooting him with a Portable Ultrasonic Weapon.**

## Question 5

::: footer
Bhagy - Brooklyn 99
:::

In Season 1 Jake Peralta discovers he owes back rent on his grandmother's appartment after failing to open the mail. How much does he owe?

**$43,000**

## Question 6

::: footer
Bhagy - Brooklyn 99
:::

Who am I?

- I am allegedly "haunted" by the spirit of a 1920s mobster's mistress.
- Charles leaves me to Jake and Amy in his will.
- I require a highly specific, disgusting daily feeding ritual and I am the secret behind the Boyle family's legendary pizza crust.


**The Motherdough**



# Victoria: The Process of Becoming a Lawyer in the Province of Ontario  {.content-background background-image="./static/law_society_of_ontario_background.png" background-size="auto 100%" style="width:fit-content;margin-top:23%;margin-left:-10%;padding-left:40px;padding-right:40px;padding-top:5px;padding-bottom:5px;border:2px solid #002b36"}

## Question 1

::: footer
Victoria - Becoming a Lawyer in Ontario
:::

Which of these is **not** a law school approved by the Convocation of the Law Society of Ontario?

:::{.incremental}
a. Lakehead University
b. Queen's University
c. Laurentian University
d. University of Ottawa
:::

## Question 2

::: footer
Victoria - Becoming a Lawyer in Ontario
:::

The named 'Law Society of Ontario' was made official on May 8, 2018. What was it called before this?

## Question 3

::: footer
Victoria - Becoming a Lawyer in Ontario
:::

Arrange the following events in chronological order:

:::{.incremental}
a. The LSAT was first administered
b. Ontario enacts the Fair Accommodations Practices Act to prevent discrimination in public services
c. The University of Ottawa establishes it's (current) Faculty of Law
d. Helen Kinnear becomes the first federally appointed female judge in Canada
e. The Bar Admission Course is established in Ontario
:::

## Question 4

::: footer
Victoria - Becoming a Lawyer in Ontario
:::

The follow is the theme song for the 1987 Canadian drama series, focusing on the professional and private lives of the partners in a small Toronto law firm. What is the name of the T.V. show?

## Question 5

::: footer
Victoria - Becoming a Lawyer in Ontario
:::

You may think there is an error in your LSAT score and therefore, wish to request an audit of your score from The Law School Admission Council. How much would this audit cost you?

## Question 6

::: footer
Victoria - Becoming a Lawyer in Ontario
:::

Who/what am I?

::: {.incremental}
- Since 1989, only 13 lawyer applicants have been rejected in Ontario based on this requirement (and none before)
- The *Armstrong* factors are an oft-cited test when hearing panels assess this requirement
- The **R. v. Ipeelee (2012)** and **R. v. Gladue (1999)** decisions rule that courts must consider unique systemic and background factors that may influence applicant's responses to this requirement

:::

## Answer 1

::: footer
Victoria - Becoming a Lawyer in Ontario
:::

Which of these is **not** a law school approved by the Convocation of the Law Society of Ontario?

:::{.incremental}
- **c. Laurentian University**
:::

## Answer 2

::: footer
Victoria - Becoming a Lawyer in Ontario
:::

The named 'Law Society of Ontario' was made official on May 8, 2018. What was it called before this?

:::{.incremental}
- **Law Society of Upper Canada**
:::

## Answer 3

::: footer
Victoria - Becoming a Lawyer in Ontario
:::

Arrange the following events in chronological order:

:::{.incremental}
d. **Helen Kinnear becomes the first federally appointed female judge in Canada (1943)**
a. **The LSAT was first administered (1948)**
c. **The University of Ottawa establishes it's (current) Faculty of Law (1953)**
b. **Ontario enacts the Fair Accommodations Practices Act to prevent discrimination in public services (1954)**
e. **The Bar Admission Course is established in Ontario (1959)**
:::

## Answer 4

::: footer
Victoria - Becoming a Lawyer in Ontario
:::

The follow is the theme song for the 1987 Canadian drama series, focusing on the professional and private lives of the partners in a small Toronto law firm. What is the name of the T.V. show?

:::{.incremental}
- **Street Legal**
:::

## Answer 5

::: footer
Victoria - Becoming a Lawyer in Ontario
:::

You may think there is an error in your LSAT score and therefore, wish to request an audit of your score from The Law School Admission Council. How much would this audit cost you?

:::{.incremental}
- **$150$**
:::

## Answer 6

::: footer
Victoria - Becoming a Lawyer in Ontario
:::

Who/what am I?

:::{.nonincremental}
- Since 1989, only 13 lawyer applicants have been rejected in Ontario based on this requirement (and none before)
- The *Armstrong* factors are an oft-cited test when hearing panels assess this requirement
- The **R. v. Ipeelee (2012)** and **R. v. Gladue (1999)** decisions rule that courts must consider unique systemic and background factors that may influence applicant's responses to this requirement
:::

## Answer 6 (cont.)

::: footer
Victoria - Becoming a Lawyer in Ontario
:::

:::{.incremental}
- **The Good character requirement**
:::

# Thanks for playing!

# OT?

# OT: Avatar: The Last Airbender {.content-background background-image="./static/atla_background.jpg" background-size="auto 100%" style="width:fit-content;margin-top:25%;padding-left:40px;padding-right:40px;padding-top:5px;padding-bottom:5px;border:2px solid #002b36"}

## Question

How long was the solar eclipse on the day of Black Sun?

:::{.incremental}
- **8 minutes**
:::

---

How many times did Aang enter the Avatar state?

:::{.incremental}
- **19 times**
:::

# Thanks for playing!