---
title: "Mastermind Trivia"
format: 
  revealjs:
    transition: slide
    background-transition: fade
    theme: solarized
    incremental: true
css: styles.css
---

```{r setup}
#| echo: false

# Load libraries ----
library(tidyverse)
```

# Bhagy: Brooklyn 99 {.content-background background-image="./static/bhagy.jpg" background-size="100%" style="width:fit-content;margin-top:25%;padding-left:40px;padding-right:40px;padding-top:5px;padding-bottom:5px;border:2px solid #002b36"}

## Question 1

::: footer
Bhagy - Brooklyn 99
:::

What is Terry's wife's name?

a. Linda
b. Susan
c. Sharon
d. Erin

## Question 2

::: footer
Bhagy - Brooklyn 99
:::

What mobile game does Holt become addicted to?

## Question 3

::: footer
Bhagy - Brooklyn 99
:::

Order these minor characters by number of episode appearances (highest to lowest)

a. Cheddar
b. Caleb John Gosche
c. Madeline Wuntch
d. Bill Hummertrout
e. Adrian Pimento

## Question 4

::: footer
Bhagy - Brooklyn 99
:::

What is happening to Charles in this [soundbite](https://youtu.be/Xu-VaMy9sFQ?si=95CPKOY63Rn5O7A9&t=914)?

## Question 5

::: footer
Bhagy - Brooklyn 99
:::

In Season 1 Jake Peralta discovers he owes back rent on his grandmother's appartment after failing to open the mail. How much does he owe?


## Question 6

::: footer
Bhagy - Brooklyn 99
:::

Who am I?

::: {.incremental}
- I am allegedly "haunted" by the spirit of a 1920s mobster's mistress.
- Charles leaves me to Jake and Amy in his will.
- I require a highly specific, disgusting daily feeding ritual and I am the secret behind the Boyle family's legendary pizza crust.
:::

## Question 1

::: footer
Bhagy - Brooklyn 99
:::

What is Terry's wife's name?

a. Linda
b. Susan
c. **Sharon**
d. Erin

## Question 2

What mobile game does Holt become addicted to?

**Kwazy Cupcakes**

## Question 3

Order these minor characters by number of episode appearances (highest to lowest)

e. Adrian Pimento (13)
c. Madeline Wuntch (12)
a. Cheddar (9)
d. Bill Hummertrout (7)
b. Caleb John Gosche (4)


## Question 4

::: footer
Bhagy - Brooklyn 99
:::

What is happening to Charles in this [soundbite](https://youtu.be/Xu-VaMy9sFQ?si=95CPKOY63Rn5O7A9&t=914)?

**Rosa is shooting him with a Portable Ultrasonic Weapon.**

## Question 5

::: footer
Bhagy - Brooklyn 99
:::

In Season 1 Jake Peralta discovers he owes back rent on his grandmother's appartment after failing to open the mail. How much does he owe?

**$43,000**

## Question 6

::: footer
Bhagy - Brooklyn 99
:::

Who am I?

- I am allegedly "haunted" by the spirit of a 1920s mobster's mistress.
- Charles leaves me to Jake and Amy in his will.
- I require a highly specific, disgusting daily feeding ritual and I am the secret behind the Boyle family's legendary pizza crust.


**The Motherdough**

# Noah: Metal Music {.content-background background-image="./static/noah.jpeg" background-size="auto 100%" background-repeat="repeat" style="width:fit-content;margin-top:25%;padding-left:40px;padding-right:40px;padding-top:5px;padding-bottom:5px;border:2px solid #002b36"}

## Question 1

::: footer
Noah - Metal Music
:::

Which of the following well-known 1960s bands is not considered a pioneer of heavy metal?

a. Led Zeppelin
b. The Rolling Stones
c. Deep Purple
d. Black Sabbath

## Question 2

::: footer
Noah - Metal Music
:::

This northern European city was considered an early metal music hub.

## Question 3

::: footer
Noah - Metal Music
:::

Order the "mainstream" appearance of each metal subgenre from earliest to latest:

a. Doom Metal
b. Alternative Metal
c. Thrash Metal
d. Death Metal
e. Grunge Metal


## Question 4

::: footer
Noah - Metal Music
:::

Which metal-inspired artist is featured in this clip?

## Question 5

::: footer
Noah - Metal Music
:::

BABYMETAL are a Nu Metal Group from Japan. As of July 13th. How many plays does their top song have on Spotify?


## Question 6

::: footer
Noah - Metal Music
:::

What am I?

::: {.incremental}
- This style evolved out of progressive metal and was popularized by the internet in the early 2000s.
- This style heavily uses syncopated riffs, distortions and polyrhythms.
- This style characteristically uses 7, 8 or even 9 stringed-guitars.
:::


## Answers

## Question 1

::: footer
Noah - Metal Music
:::

Which of the following well-known 1960s bands is not considered a pioneer of heavy metal?

a. Led Zeppelin
b. **The Rolling Stones**
c. Deep Purple
d. Black Sabbath

## Question 2

::: footer
Noah - Metal Music
:::

This northern European city was considered an early metal music hub.

**Gothenburg, Sweden**

## Question 3

::: footer
Noah - Metal Music
:::

Order the "mainstream" appearance of each submetal genre from earliest to latest:

a. Thrash Metal (1980s)
b. Death Metal (mid 1980s)
c. Doom Metal (late 1980s - early 90s)
d. Grunge Metal (mid 1990s)
e. Alternative Metal (early 2000s)

## Question 4

::: footer
Noah - Metal Music
:::

Which metal-inspired artist is featured in this clip?

**Evanescence**

## Question 5

::: footer
Noah - Metal Music
:::

BABYMETAL are a Nu Metal Group from Japan. As of July 13th. How many plays does their top song have on Spotify?

143,910,465

## Question 6

::: footer
Noah - Metal Music
:::

What am I? 

- This style evolved out of progressive metal.
- This style heavily uses syncopated riffs, distortions and polyrhythms.
- This style characteristically uses 7, 8 or even 9 stringed-guitars.

**Djent**


# Hayley: Grade 9 Geography {.content-background background-image="./static/hayley.jpg" background-size="100%" style="width:fit-content;margin-top:25%;padding-left:40px;padding-right:40px;padding-top:5px;padding-bottom:5px;border:2px solid #002b36"}

## Question 1

::: footer
Hayley - Grade 9 Geography
:::

Which province produces the most hydroelectric power?

a. Ontario
b. Quebec
c. British Columbia
d. Alberta

## Question 2

::: footer
Hayley - Grade 9 Geography
:::

Which natural resource industry employs the most people in Canada?

## Question 3

::: footer
Hayley - Grade 9 Geography
:::

Order these Canadian demographic events:

a. Canada's population surpasses 30 million
b. Millenials outnumbered Baby Boomers
c. Canada's total fertility rate drops below 2 babies per female
d. The first Gen Alpha is born
e. Nunavut becomes a territory

## Question 4

::: footer
Hayley - Grade 9 Geography
:::

What location is "discovered" in this [Heritage Minute](https://www.historicacanada.ca/productions/minutes/jean-nicollet)?

## Question 5

::: footer
Hayley - Grade 9 Geography
:::

How many square km is the Canadian shield?

## Question 6

::: footer
Hayley - Grade 9 Geography
:::

What am I?

::: {.incremental}
- I am shared by Canada and the US and am named after a Greek explorer.
- I last caused a major earthquake in 1700.
- I am a microplate in the ring of fire.
:::

## Answers

## Question 1

::: footer
Hayley - Grade 9 Geography
:::

Which province produces the most hydroelectric power?

a. Ontario
b. **Quebec**
c. British Columbia
d. Alberta

## Question 2

::: footer
Hayley - Grade 9 Geography
:::

Which natural resource industry employs the most people in Canada?

**Minerals and metals**

## Question 3

::: footer
Hayley - Grade 9 Geography
:::

Order these Canadian demographic events:

a. Canada's total fertility rate drops below 2 babies per female (1972)
b. Nunavut becomes a territory (1999)
c. Canada's population surpasses 30 million (2001)
d. The first Gen Alpha is born (2010)
e. Millenials outnumbered Baby Boomers (2023)

## Question 4

::: footer
Hayley - Grade 9 Geography
:::

What location is "discovered" in this [Heritage Minute](https://www.historicacanada.ca/productions/minutes/jean-nicollet)?

**Lake Michigan**

## Question 5

::: footer
Hayley - Grade 9 Geography
:::

How many square km is the Canadian shield?

**8,000,000 km^2**

## Question 6

::: footer
Hayley - Grade 9 Geography
:::

What am I? 

- I am shared by Canada and the US and am named after a Greek explorer.
- I last caused a major earthquake in 1700.
- I am a microplate in the ring of fire.

**Juan de Fuca Plate**


# Thanks for playing!
